WORD_BANK = {
    "Animals": [
        "ELEPHANT", "GIRAFFE", "KANGAROO", "CROCODILE", "ALLIGATOR",
        "PENGUIN", "DOLPHIN", "CHEETAH", "LEOPARD", "OCTOPUS",
        "BUTTERFLY", "CHAMELEON", "RHINOCEROS", "SQUIRREL", "WOODPECKER",
        "HAMSTER", "PELICAN", "FLAMINGO", "PORCUPINE", "SEAHORSE",
    ],
    "Programming": [
        "PYTHON", "FUNCTION", "VARIABLE", "PACKAGE", "OBJECT",
        "BOOLEAN", "ITERATION", "COMPILER", "DEBUGGER", "ALGORITHM",
        "DATABASE", "NETWORK", "LOOP", "CONSTANT", "INTEGER",
        "FRAMEWORK", "PYINSTALLER", "REGISTRY", "SCENE", "PERSISTENCE",
    ],
    "Countries": [
        "AUSTRALIA", "BRAZIL", "CANADA", "DENMARK", "ETHIOPIA",
        "FINLAND", "GERMANY", "HUNGARY", "INDONESIA", "JAPAN",
        "KENYA", "MALAYSIA", "NORWAY", "PORTUGAL", "ROMANIA",
        "SINGAPORE", "THAILAND", "UGANDA", "VIETNAM", "ZAMBIA",
    ],
    "Games": [
        "ARCADE", "SNAKE", "TETRIS", "MINESWEEPER", "ASTEROIDS",
        "BREAKOUT", "BATTLESHIPS", "SUDOKU", "HANGMAN", "PONG",
        "CONNECT", "WHACAMOLE", "MEMORY", "INVADERS", "SIMON",
        "LAUNCHER", "PUZZLE", "CONTROLLER", "HIGHSCORE", "POWERUP",
    ],
}