from __future__ import annotations

WORDS: dict[str, list[str]] = {
    "Animals": [
        "ELEPHANT",
        "KANGAROO",
        "PENGUIN",
        "CROCODILE",
        "DOLPHIN",
        "GIRAFFE",
        "LEOPARD",
        "RACCOON",
        "PLATYPUS",
        "OSTRICH",
        "CHAMELEON",
        "ALLIGATOR",
    ],
    "Space": [
        "GALAXY",
        "ORBIT",
        "SATELLITE",
        "ASTRONAUT",
        "NEBULA",
        "TELESCOPE",
        "METEOR",
        "ECLIPSE",
        "COMET",
        "GRAVITY",
        "ROCKET",
        "SUPERNOVA",
    ],
    "Technology": [
        "PYTHON",
        "DATABASE",
        "NETWORK",
        "ALGORITHM",
        "BROWSER",
        "COMPILER",
        "ENCRYPTION",
        "INTERFACE",
        "SOFTWARE",
        "DEBUGGER",
        "HARDWARE",
        "FRAMEWORK",
    ],
    "Fantasy": [
        "DRAGON",
        "CASTLE",
        "WIZARD",
        "KINGDOM",
        "PHOENIX",
        "SORCERER",
        "ENCHANTMENT",
        "TREASURE",
        "PALADIN",
        "GOBLIN",
        "SPELLBOOK",
        "WARLOCK",
    ],
    "Sports": [
        "BASKETBALL",
        "VOLLEYBALL",
        "SWIMMING",
        "GYMNASTICS",
        "CRICKET",
        "FOOTBALL",
        "BADMINTON",
        "SKATEBOARD",
        "CLIMBING",
        "TRIATHLON",
    ],
}